name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes E2E com Cypress
        run: npx cypress run

      - name: Rodar testes de API com k6
        run: npx k6 run k6/test.js

      - name: Rodar testes móveis com Appium
        run: npx wdio wdio.conf.js
